version: '3.7'
services:
  api:
    ports:
      - "81:81"
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./schema.graphql:/schema.graphql
    env_file:
      .env.example
    container_name: api
  frontend:
    ports:
      - "82:82"
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      .env.example
    container_name: frontend
  solution-web:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - '80:80'
    container_name: solution-web
    depends_on:
      - api
      - frontend