version: '3.7'
services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mall
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    ports:
      - "81:81"
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      .env.example
    container_name: api
    depends_on:
      - db
  frontend:
    ports:
      - "82:82"
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      .env.example
    container_name: frontend
  solution-web:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - '80:80'
    container_name: solution-web
    depends_on:
      - api
      - frontend