version: '3.7'
services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "81:81"
    volumes:
      - ./schema.graphql:/schema.graphql
    env_file:
      .env.example
    networks:
      - nginx_network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "82:82"
    env_file:
      .env.example
    networks:
      - nginx_network

  solution-web:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - '80:80'
    container_name: solution-web
    depends_on:
      - api
      - frontend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge